---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starterapp-python
spec:
  selector:
    matchLabels:
      app: starterapp-python
  template:
    metadata:
      labels:
        app: starterapp-python
    spec:
      containers:
      - name: starterapp-python
        image: quay.io/cloud-native-robotz-hackathon/starter-app-python:master
        env:
        - name: INFERENCING_API
          value: "http://server.triton.svc.cluster.local"
        - name: ROBOT_API
          value: "http://robot.local:5000"
        - name: ROBOT_NAME
          value: "NONE"
        - name: INFERENCING_API_TOKEN
          value: "NONE"
