---
kind: Service
apiVersion: v1
metadata:
  name: starterapp-python
spec:
  ports:
  - protocol: TCP
    name: 8080-tcp
    port: 8080
    targetPort: 8080
  selector:
    app: starterapp-python 
  sessionAffinity: None
  type: ClusterIP

