---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton
spec:
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      volumes:
      - name: models
        emptyDir: {}
      initContainers:
      - image: quay.io/cloud-native-robotz-hackathon/model-container:trained
        imagePullPolicy: IfNotPresent
        name: model-container
        volumeMounts:
        - name: models
          mountPath: /dst/
      containers:
      - name: triton
        ports:
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8002
        command:
        - tritonserver
        - --model-repository
        - /models
        image: quay.io/cloud-native-robotz-hackathon/tritonserver:24.08-py3
        volumeMounts:
        - name: models
          mountPath: /models
