apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: triton-server
  name: triton-server
spec:
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: server
    weight: 100
  wildcardPolicy: None
